server:
  port: 0

grpc:
  server:
    port: 0
    reflection-service-enabled: true

spring:
  application:
    name: collector
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      retry:
        useRandomPolicy: true
        max-interval: 6000

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost
    instance-id: ${spring.application.name}:${random.value}
    leaseRenewalIntervalInSeconds: 10

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: ru.practicum.ewm.stats.avro.UserActionAvroSerializer
    acks: ${KAFKA_PRODUCER_ACKS:all}
    retries: ${KAFKA_PRODUCER_RETRIES:3}
    linger-ms: ${KAFKA_PRODUCER_LINGER_MS:100}
    max-in-flight-requests-per-connection: ${KAFKA_PRODUCER_MAX_IN_FLIGHT:1}
    delivery-timeout-ms: ${KAFKA_PRODUCER_DELIVERY_TIMEOUT:120000}
    request-timeout-ms: ${KAFKA_PRODUCER_REQUEST_TIMEOUT:30000}
    enable-idempotence: ${KAFKA_PRODUCER_ENABLE_IDEMPOTENCE:true}

  topics:
    output-topic: stats.user-actions.v1

logging:
  level:
    ru.practicum: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level --- [%thread] %logger{36} : %msg%n"