kafka:
  bootstrap-servers: localhost:9092

  consumer:
    group-id: aggregator-consumer
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: ru.practicum.serialization.UserActionAvroDeserializer
    enable-auto-commit: false

  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: ru.practicum.serialization.SpecificRecordSerializer
    acks: all
    retries: 3
    linger-ms: 100
    max-in-flight-requests-per-connection: 1
    delivery-timeout-ms: 120000
    request-timeout-ms: 30000
    enable-idempotence: true

  topics:
    input-topic: stats.user-actions.v1
    output-topic: stats.events-similarity.v1